version: 2.1
jobs:
  build:
    docker:
    - image: tm604/perl-dzil
    steps:
    - checkout
    - restore_cache:
        key: cpan-{{ checksum "cpanfile" }}
    - run:
        command: |
          cpanm -n $(dzil authordeps)
          cpanm --installdeps .
          dzil build && perl Makefile.PL && make && make test
        name: Run tests
    - save_cache:
        key: cpan-{{ checksum "cpanfile" }}
        paths:
            - /usr/local/lib/perl5/site_perl
